### ISSUE TITLE
MemoryTransport mutable default value

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-py#19]
### Expected vs. Actual Behavior
Expected: Two separate instances of a MemoryTransport contain separate data.
Actual: The dict mutable default value is leaking value between the two instances.

Describe the problem here.

In python the default values are evaluated in parsing time. This results that mutable default values (that are created as reference types in the background, not copy types) are only created once on a single memory address. If a function has a mutable default value, ie. empty list. It is created once if that list is mutated, this can result in unexpected behaviour.

### Reproduction Steps & System Config (win, osx, web, etc.)
Just run this script

```
from pydantic.dataclasses import dataclass
from abc import ABC
from typing import Dict

@dataclass
class AbsDefaultValue(ABC):
    """Just an abstract base."""

class WrongDefaultValue(AbsDefaultValue):
    mutable_default: Dict[str,str] = {}

if __name__ == "__main__":
    
    a = WrongDefaultValue()
    b = WrongDefaultValue()

    a.mutable_default["foo"] = "bar"

    print(a.mutable_default)
    print(b.mutable_default)
```

### Proposed Solution (if any)

Pydantic actually protects from this behaviour with its internal check. So the first fix is, to add @dataclass decorator to the MemoryTransport class. In fact each class that is intended to be a dataclass must be decorated as a dataclass.

By changing the code to the proper behaviour, raises a meaningful exception.  
```
from pydantic.dataclasses import dataclass
from abc import ABC
from typing import Dict

@dataclass
class AbsDefaultValue(ABC):
    """Just an abstract base."""

@dataclass
class WrongDefaultValue(AbsDefaultValue):
    mutable_default: Dict[str,str] = {}
```

This also affects the ServerTransport implementation with possibly a much greater impact, since there, the workers are shared across Transport instances.

I guess currently multiple transport are not initiated, so this hasn't come up yet, but it will cause serious bugs in the long run.

The fix is fortunately quite easy. You have to explicitly pass in a default factory `callable` that will be called by pydantic in the post init hook. 

```
import dataclasses
from pydantic.dataclasses import dataclass
from pydantic import Field
from abc import ABC
from typing import Dict, List

@dataclass
class AbsDefaultValue(ABC):
    """Just an abstract base."""

@dataclass
class WrongDefaultValue(AbsDefaultValue):
    mutable_default: Dict[str, str] = dataclasses.field(default_factory=dict)

if __name__ == "__main__":

    print(dict())
    
    a = WrongDefaultValue()
    b = WrongDefaultValue()

    a.mutable_default["foo"] = "bar"
    b.mutable_default["foo"] = "not so bar"

    print(a.mutable_default)
    print(b.mutable_default)
```

**Comment by izzylys** [comment]
ah thank you very much for bringing this up! I had intended to change `AbstractTransport` to inherit from pydantic's `BaseModel` to resolve this but had not gotten around to it. thanks for the reminder! if my understanding is correct, I believe doing so will handle this issue?

**Comment by gjedlicska** [comment]
I would reopen this issue, your solution is not technically good. You should not intherit from Pydantic `BaseClass` and `dataclass` at the same time.

**Comment by izzylys** [comment]
hey @gjedlicska!

If you have a look at the code, I am not inheriting from `BaseClass` and `dataclass` at the same time as that is ill advised according to the docs. the `AbstractTransport` is instead only inheriting from `BaseClass`

Regarding the default values, I believe that syntax that you listed there is only necessary for dynamic default values that are _different_ for each instance. Default empty dictionaries or lists would not need this.

I would be interested to hear your views on the `BaseModel` more generally. I quite like many of the features that using `BaseModel` provides which is why I am using it as the base, but am happy to hear other ideas!

**Comment by gjedlicska** [comment]
You are quite right, I missed that change in your commit regarding migrating from dataclass to BaseClass. Sorry about that.

On the other hand, default values, that are copy types (loosly translated, not primitive types) has to be initialized via a default factory.  List and dict should be initialized via a default factory callable.

**Comment by gjedlicska** [comment]
On the topic of using `BaseModel` as a base for internal classes, it is a question of tradeoffs. Each nicety pydantic provides comes with a cost. My view is that pydantic has a big cost both at runtime and syntax wise (mandatory kwargs, which is fine for ie. parsing incoming models for APIs). 
The internal models many times are a pain to constantly initialize with only kwargs. Also the constant runtime validation regarding type and value is not really required on internal classes.
I've been in favour of using python default dataclass or attrs for internal classes for the usecases like the Transport object and its derivatives. I know it is a separate dependency and a bit different toolkit but ease of use outweighs it IMHO.
