### ISSUE TITLE
🌀 Concurrency for serialisation and transports

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-py#6]
Transports should not be blocking in order for decomposition / serialisation to happen concurrently with saving objects using the transports. The serialiser working its way through a root object with loads of child objects should be able to chug along with the decomposition and serialisation and chuck finished objects into a queue for the transport to pick up and send as they become available. However, we don't want to complicate usage for the end user meaning this magic should be somehow contained. How do we want to do this?

**Comment by gjedlicska** [comment]
Hey, if I get this right, I think this should be split into multiple parts, atleast 2. One is something like #45 and another would be some form of background processing / queuing for serialization and sending. That happens separately of the main python thread, to unblock the host app. The first is rather straight forward, the second could be a bit tricky, depending on how the host app handles it.
