### ISSUE TITLE
🧪 ❌ Some tests are no longer passing on CI or locally

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-py#83]
### Expected vs. Actual Behavior

Some tests are failing on CI and locally too. See CI log for more details: https://app.circleci.com/pipelines/github/specklesystems/speckle-py/127/workflows/adc4e3d8-6c81-48a1-b3b4-b391295367b6/jobs/440

### Reproduction Steps & System Config (win, osx, web, etc.)

Run your tests and see them 💥 . Any OS will do, tested in Mac/Windows and CI is Linux.

### Proposed Solution (if any)

I have absolutely no idea what's going on, I'll leave it to @izzylys' magic.

**Comment by izzylys** [comment]
thanks for reporting! will have a look this afternoon 👍
