### ISSUE TITLE
Manually add an account on GNU/Linux

### ISSUE THREAD

**Issue by CyrilWaechter** [specklesystems/speckle-py#95]
From [docs](https://speckle.guide/user/manager.html#adding-accounts-manually) I see that there is apparently no SpeckleManager for GNU/Linux systems. Although I see also that it is possible to [add an account manually](https://speckle.guide/user/manager.html#adding-accounts-manually). 

Can you please point me out where in the code it looks for this .json file to see where I need to put it or if code needs to be modified ?

**Comment by CyrilWaechter** [comment]
> If you're curious, the .net [implementation is here](https://github.com/specklesystems/speckle-sharp/blob/master/Core/Core/Credentials/AccountManager.cs#L134).

I do not know the .net way to do find cross-platform settings folder but you can see how I did in python for v1 here: https://github.com/speckleworks/PySpeckle/commit/2c9033acdeb60ce2deb39bb612416d980a3c6811

**Comment by izzylys** [comment]
Hi Cyril!

The method that locates the path for your os is [this one in the sqlite transport](https://github.com/specklesystems/speckle-py/blob/5a9b4137da5558d8f460e305401ff9417d8679a5/specklepy/transports/sqlite.py#L52-L67). It is using the `appdirs` package with a special case for mac (as per the comment). In theory, it should be locating the correct path on mac, win, and linux although I have not had a linux user test it (just the circle ci job 😅). If the `appdirs` package isn't working as expected, I would be totally grateful for a pr to fix this method if you get a chance! 

The py sdk does not have a specific helper method to add a local account as the intention is for this to only be done via manager (though I can change this if @didimitrie is ok with it?) but you can use the sqlite transport with the accounts scope (`SQLiteTransport(scope="Accounts")`) to save an account object to the local db yourself.

Hopefully that's helpful, but let me know if anything is still unclear ✨

**Comment by CyrilWaechter** [comment]
`appdirs` seems correct but your modified version not. We can have a talk about all this if you like.

I was not able to create an account manually. I am not sure to understand all required parameters especially `refreshToken` and `Account` `id` versus `UserInfo` `id` Here is what I tried:
```python
>>> from specklepy.transports.sqlite import SQLiteTransport
>>> transport = SQLiteTransport(scope="Accounts")
>>> from specklepy.api.credentials import Account
>>> from specklepy.api.models import ServerInfo
>>> from specklepy.api.credentials import UserInfo
>>> user_info = UserInfo(name="<my_full_name>", email="<my_email>", company="<my_company_name>", id="<my_id?>")
>>> server_info = ServerInfo(name="Speckle.xyz", url="https://speckle.xyz")
>>> account = Account(isDefault=True, token="<my_personal_token>", refreshToken="<my_personal_token?>", serverInfo=server_info, userInfo=user_info, id="<my_id?>")
>>> from specklepy.api import operations
>>> operations.send(base=account, transports=[transport])
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/cyril/.config/blender/2.92/scripts/modules/specklepy/api/operations.py", line 37, in send
    hash, _ = serializer.write_json(base=base)
  File "/home/cyril/.config/blender/2.92/scripts/modules/specklepy/serialization/base_object_serializer.py", line 37, in write_json
    hash, obj = self.traverse_base(base)
  File "/home/cyril/.config/blender/2.92/scripts/modules/specklepy/serialization/base_object_serializer.py", line 54, in traverse_base
    object_builder.update(speckle_type=base.speckle_type)
AttributeError: 'Account' object has no attribute 'speckle_type'
```

**Comment by izzylys** [comment]
Hey Cyril!

Sure, would be happy to talk about the `appdirs` thing! I am honestly not knowledgeable about this and would appreciate help in getting to the bottom of it.

For the accounts, sorry I think there was a bit of a misunderstanding on my end. specklepy does not have the ability to read accounts from json files in the `Speckle/Accounts` path. I have added this to my todo list and will add it asap!

However, you can manually save an account using the sqlite transport using the example acct format from [the docs you linked](https://speckle.guide/user/manager.html#adding-accounts-manually). However, you'll need to change the `Account` model in `credentials` to not require the refresh token, id, and `isDefault` flag (which I have sneakily just merged in to main, so you can pull from latest if you'd like). 

```py
from specklepy.transports.sqlite import SQLiteTransport

acct = """
{
  "token": "YOUR-TOKEN-HERE",
  "serverInfo": {
    "name": "Server Name",
    "company": "Company Name",
    "url": "https://YOUR-SERVE-URL-HERE"
  },
  "userInfo": {
    "id": "YOUR-USER-ID",
    "name": "First Last",
    "email": "firstlast@email.com"
  }
}
"""

transport = SQLiteTransport(scope="Accounts")
transport.save_object("accountId", acct)  # id just needs to be a unique identifier, so just using your user id should be fine 

```

It's a bit of a hack tho, so I will be adding reading accounts from json very soon!

**Comment by CyrilWaechter** [comment]
Hi Izzy,
> Sure, would be happy to talk about the `appdirs` thing! I am honestly not knowledgeable about this and would appreciate help in getting to the bottom of it.

Sure I sent you a message on forum to get in touch.

> For the accounts, sorry I think there was a bit of a misunderstanding on my end. specklepy does not have the ability to read accounts from json files in the `Speckle/Accounts` path. I have added this to my todo list and will add it asap!

Great!

> However, you can manually save an account using the sqlite transport using the example acct format from [the docs you linked](https://speckle.guide/user/manager.html#adding-accounts-manually). However, you'll need to change the `Account` model in `credentials` to not require the refresh token, id, and `isDefault` flag (which I have sneakily just merged in to main, so you can pull from latest if you'd like).
> 
> ```python
> from specklepy.transports.sqlite import SQLiteTransport
> 
> acct = """
> {
>   "token": "YOUR-TOKEN-HERE",
>   "serverInfo": {
>     "name": "Server Name",
>     "company": "Company Name",
>     "url": "https://YOUR-SERVE-URL-HERE"
>   },
>   "userInfo": {
>     "id": "YOUR-USER-ID",
>     "name": "First Last",
>     "email": "firstlast@email.com"
>   }
> }
> """
> 
> transport = SQLiteTransport(scope="Accounts")
> transport.save_object("accountId", acct)  # id just needs to be a unique identifier, so just using your user id should be fine 
> ```

Great much simpler than what I did!
